before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  # - psql -c 'create database fresh_cabbage_test;' -U postgres

  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate"

language: ruby

rvm:
  - 2.2.2

services:
  - postgresql
